// using UnityEngine;
// using System.Collections;

// public class EnemyIdleState : EnemyBaseState
// {
//     //wait for a random amount of seconds (later on, while playing an animation)

//     private float initialHealth;
//     private IEnumerator idleCoroutine;
//     private IEnumerator lookCoroutine;
//     private float lookTime = 2f;
//     public override void EnterState(EnemyStateManager enemy)
//     {
//         initialHealth = enemy.healthComponent.health;
//         Debug.Log("Now in Idle State");
//         idleCoroutine = IdleLook(enemy, lookTime);
//         enemy.StartCoroutine(idleCoroutine);
//         //once the enemy is done. switch to patrol state
//     }

//     //transfer to patrol state
//     public override void UpdateState(EnemyStateManager enemy)
//     {
//         //how to find out if the player is the reason this target gets shot?
//         //if player is in line of site or damage is taken (health < than initial health)
//         if(enemy.healthComponent.health < initialHealth){
//             Debug.LogFormat("Ow... {0}'s health is now {1} :(", enemy.name, enemy.healthComponent.health);
//             //temporary - will switch to combat state if damaged
//             enemy.StopCoroutine(idleCoroutine);
//             enemy.StopCoroutine(lookCoroutine);
//             enemy.SwitchState(enemy.CombatState);
//         }
//     }

//     //should looking be a separate state? like, sweep state where the enemy sweeps an area to look around?
//     //then switches to partrol state which raycasts around to check for a direction, then walks in that direction?
//     //so that during combat, when enemies have lost sight of the player for a number of seconds, they can enter sweep state?
//     IEnumerator IdleLook(EnemyStateManager enemy, float lookTime, float lookLength = 3f, float lookRadius = 179f)
//     {
//         lookRadius = lookRadius / 2; // <-- randomise the initial orientation with a random seed generated by each instance of the enemy class so the initial direction is unique for each instance
//         //variable for looking to one side
//         float firstLook = lookLength / 6;
//         //covering distance from the first side to the second side
//         float secondLook = firstLook * 2;        

//         //if enemy is shot at - stop these coroutines, then stop the partrol look coroutine in Enterstate and shift to combatstate
//         //can you nest these coroutines in itself recursively?
//         lookCoroutine = SweepArea(enemy, firstLook, lookRadius);
//         enemy.StartCoroutine(lookCoroutine);
//         yield return new WaitForSeconds(lookTime);
//         lookCoroutine = SweepArea(enemy, secondLook, -lookRadius * 2);
//         enemy.StartCoroutine(lookCoroutine);
//         yield return new WaitForSeconds(lookTime);
//         lookCoroutine = SweepArea(enemy, firstLook, lookRadius);
//         enemy.StartCoroutine(lookCoroutine);

//     }

    // IEnumerator SweepArea(EnemyStateManager enemy, float turnLength = 3f, float lookRadius = 179f, float lookLength = 1)
    // {
    //     //first look

    //     Vector3 byAngles = new Vector3(0f, lookRadius, 0f);
    //     Quaternion fromAngle = enemy.transform.rotation;
    //     Quaternion toAngle = Quaternion.Euler(enemy.transform.eulerAngles + byAngles);
    //     for(var t = 0f; t < 1; t += Time.deltaTime / turnLength)
    //     {
    //         enemy.transform.rotation = Quaternion.Lerp(fromAngle, toAngle, t);
    //         yield return null;
    //     }
    // }
// }
