using UnityEngine;
using System.Collections;


public class EnemyPatrolState : EnemyBaseState
{
    float patrolSpeed = 3;
    private float lookTime = 2f;
    bool seesPlayer = false;
    //if Enemy sees player, is alerted or shot, switch to combat state
    //else, randomly pathfind, then occasionally switch to idle state
    public override void EnterState(EnemyStateManager enemy)
    {
        seesPlayer = false;
        Debug.LogFormat("Must have been the wind...");
        enemy.StartCoroutine(PatrolLook(enemy, lookTime));
    }

    //step 1: pathfind - look for a suitable direction to walk
    //step 2: walk - walk in the given direction for a set (pseudorandom) distance
    //step 3: pathfind again
    //initialise sweeparea and patrollook coroutines into variables. When shot in update,
    //stop both sweeparea and patrollook coroutines with stop coroutine (?)

    //how do you handle enemy movement going up and down inclines?

    public override void UpdateState(EnemyStateManager enemy)
    {
        
    }


    //should looking be a separate state? like, sweep state where the enemy sweeps an area to look around?
    //then switches to partrol state which raycasts around to check for a direction, then walks in that direction?
    //so that during combat, when enemies have lost sight of the player for a number of seconds, they can enter sweep state?
    private bool looking = false;
    IEnumerator PatrolLook(EnemyStateManager enemy, float lookTime, float lookLength = 3f, float lookRadius = 179f)
    {
        lookRadius = lookRadius / 2; // <-- randomise the initial orientation with a random seed generated by each instance of the enemy class so the initial direction is unique for each instance
        //variable for looking to one side
        float firstLook = lookLength / 6;
        //covering distance from the first side to the second side
        float secondLook = firstLook * 2;        

        //if enemy is shot at - stop these coroutines, then stop the partrol look coroutine in Enterstate and shift to combatstate
        enemy.StartCoroutine(SweepArea(enemy, firstLook, lookRadius));
        yield return new WaitForSeconds(lookTime);
        enemy.StartCoroutine(SweepArea(enemy, secondLook, -lookRadius * 2));
        yield return new WaitForSeconds(lookTime);
        enemy.StartCoroutine(SweepArea(enemy, firstLook, lookRadius));

    }

    IEnumerator SweepArea(EnemyStateManager enemy, float turnLength = 3f, float lookRadius = 179f, float lookLength = 1)
    {
        //first look
        Vector3 byAngles = new Vector3(0f, lookRadius, 0f);
        Quaternion fromAngle = enemy.transform.rotation;
        Quaternion toAngle = Quaternion.Euler(enemy.transform.eulerAngles + byAngles);
        for(var t = 0f; t < 1; t += Time.deltaTime / turnLength)
        {
            enemy.transform.rotation = Quaternion.Lerp(fromAngle, toAngle, t);
            yield return null;
        }
    }

    //pick a random direction 90, -90 or 180 degrees away from enemy? raycast to check if it is a wall.
    //if it is clear - turn to that direction and continue to move in that direction.
    void PatrolMove(EnemyStateManager enemy)
    {   
        //if their x coordinate is negative, they will not exhibit movement.
        //this means one of these vectors are misinterpreting position
        //for magnitude?
        //temporary variables - could move into parameter
        float randomRadius = 15f;
        Vector3 randomMove = Random.insideUnitSphere * randomRadius;
        
        enemy.transform.rotation = Quaternion.Euler(0, Random.Range(0, 360), 0);
        Vector3 moveDirection = patrolSpeed * new Vector3(randomMove.x, 0, randomMove.z);
        //I can multiply move Direction with a transform to rotate it

        //float step = patrolSpeed * Time.deltaTime;
        //enemy.transform.position = Vector3.MoveTowards(enemy.transform.position, new Vector3(10, 0, 0), step); //this only occurs once a frame - should movement be in update?
        enemy.transform.Translate(enemy.transform.rotation * moveDirection * Time.deltaTime);
    }

    //patrolling method:
    /**
    to make this follow a recursive method - pass a number into a function denoting
    the amount of times you want the enemy to move. each time the method is called,
    reduce the number by 1 and stop recursing when the number is equal to 0;
    inside the method:
    randomize this a number of times between 3 and 10:
        use this method:
        Vector2 gunSpread = Random.insideUnitCircle * spreadRadius;
            gunSpread.z = 1;
            Vector2 shotDirection = (gunSpread - Vector3.zero).normalized;
            shotDirection = playerCamera.transform.rotation * shotDirection;

        to find a random vector.
        find a random magnitude to multiply the distance by
        move in that direction
        
        move in that direction by plugging it kinda into this:
        controller.Move(transform.rotation * finalMove * Time.deltaTime);


    **/
    //using recursion, make the enemy move randomly a random amount of times between
    //3-10

    //pick a random direction on a vector 2 axis and a random amount of time
    //move in that direction in correlation to patrol speed magnitude

    //make a look function. inbetween patrolling, look around for both the player and
    // it's possible pathfinding directions?
}
